# Teena Bokde
# Data Science - Batch Oct 2024 (Pune) - Assignment 10

# Association Rules

# Task 1: Data Preprocessing

Importing Libraries

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Online retail.xlsx')
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [ ]:
missing_values = df.isnull().sum()  # Handling the missing values
missing_values

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [ ]:
df.columns

Index(['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'], dtype='object')

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7492  burgers,salmon,pancakes,french fries,frozen sm...
7493  turkey,burgers,dessert wine,shrimp,pasta,tomat...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[5175 rows x 1 columns]

In [ ]:
transaction = df.iloc[:, 0].apply(lambda x: x.split(',')) # Convert the data to a list of lists (each transaction is a list of items)
transaction

0                              [burgers, meatballs, eggs]
1                                               [chutney]
2                                       [turkey, avocado]
3       [mineral water, milk, energy bar, whole wheat ...
4                                        [low fat yogurt]
                              ...
7492    [burgers, salmon, pancakes, french fries, froz...
7493    [turkey, burgers, dessert wine, shrimp, pasta,...
7495                    [butter, light mayo, fresh bread]
7496    [burgers, frozen vegetables, eggs, french frie...
7499    [eggs, frozen smoothie, yogurt cake, low fat y...
Name: shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil, Length: 5175, dtype: object

# Task 2: Association Rule Mining:

In [ ]:
!pip install mlxtend

Collecting mlxtend
  Obtaining dependency information for mlxtend from https://files.pythonhosted.org/packages/1c/07/512f6a780239ad6ce06ce2aa7b4067583f5ddcfc7703a964a082c706a070/mlxtend-0.23.1-py3-none-any.whl.metadata
  Downloading mlxtend-0.23.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (1.11.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (2.0.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (3.7.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\pavan\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pavan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\pavan\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\pavan\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pavan\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\pavan\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.4 MB 2.6 MB/s eta 0:00:01
   ------ --------------------------------- 0.2/1.4 MB 3.0 MB/s eta 0:00:01
   -------- ------------------------------- 0.3/1.4 MB 2.7 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.4 MB 2.1 MB/s eta 0:00:01
   ----------- ---------------------------- 0.4/1.4 MB 2.0 MB/s eta 0:00:01
   ----------- ---------------------------- 0.4/1.4 MB 2.0 MB/s eta 0:00:01
   ----------- ---------------------------- 0.4/1.4 MB 2.0 MB/s eta 0:00:01
   ------------ --------------------------- 0.4/1.4 MB 1.3 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.4 MB 1.3 MB/s eta 0:00:01
   -------------------- ------------------- 0.7/1.4 MB 1.6 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.4 MB 1.6 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.4 MB 1.6 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.4 MB 1.6 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 1.3 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 1.3 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 1.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.4 MB 1.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.4 MB 1.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.4 MB 1.3 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 1.4/1.4 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 1.4 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.1

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

In [ ]:
te = TransactionEncoder()   # Convert the transactions to a one-hot encoded dataframe
te_ary = te.fit(transaction).transform(transaction)
df_encoded = pd.DataFrame(te_ary, columns = te.columns_)

In [ ]:
te

TransactionEncoder()

In [ ]:
te_ary

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [ ]:
df_encoded

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5171,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
frequent_itemsets = apriori(df_encoded, min_support = 0.01, use_colnames = True)
frequent_itemsets

      support                               itemsets
0    0.029179                              (almonds)
1    0.011014                    (antioxydant juice)
2    0.045797                              (avocado)
3    0.012560                                (bacon)
4    0.015459                       (barbecue sauce)
..        ...                                    ...
431  0.014686  (spaghetti, olive oil, mineral water)
432  0.016618   (spaghetti, mineral water, pancakes)
433  0.012367     (spaghetti, mineral water, shrimp)
434  0.010821       (spaghetti, soup, mineral water)
435  0.013527   (spaghetti, mineral water, tomatoes)

[436 rows x 2 columns]

In [ ]:
rules = association_rules(frequent_itemsets, metric = 'lift', min_threshold = 1)

rules = rules[(rules['confidence'] >= 0.5) & (rules['lift'] >= 1.2 )]

rules_sorted = rules.sort_values(by = 'lift', ascending = False)
rules_sorted

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
717,"(frozen vegetables, ground beef)",(spaghetti),0.024541,0.229565,0.012560,0.511811,2.229480,0.006927,1.578149,0.565339
793,"(soup, milk)",(mineral water),0.021449,0.299710,0.012367,0.576577,1.923781,0.005939,1.653876,0.490716
711,"(frozen vegetables, ground beef)",(mineral water),0.024541,0.299710,0.013333,0.543307,1.812775,0.005978,1.533393,0.459640
828,"(spaghetti, soup)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,0.004624,1.469236,0.436362
764,"(pancakes, ground beef)",(mineral water),0.020870,0.299710,0.010821,0.518519,1.730067,0.004566,1.454448,0.430982
500,"(chocolate, chicken)",(mineral water),0.021256,0.299710,0.011014,0.518182,1.728943,0.004644,1.453432,0.430768
775,"(olive oil, milk)",(mineral water),0.024155,0.299710,0.012367,0.512000,1.708317,0.005128,1.435020,0.424892
599,"(olive oil, chocolate)",(mineral water),0.023575,0.299710,0.011981,0.508197,1.695627,0.004915,1.423923,0.420153
752,"(milk, ground beef)",(mineral water),0.031691,0.299710,0.016039,0.506098,1.688623,0.006541,1.417871,0.421148
668,"(eggs, ground beef)",(mineral water),0.028792,0.299710,0.014493,0.503356,1.679475,0.005863,1.410043,0.416570

In [ ]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)  # Setting thresholds for confidence (e.g., 0.2) and lift (e.g., 1.0)
rules = rules[rules['lift'] > 1]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(almonds),(mineral water),0.029179,0.299710,0.010821,0.370861,1.237399,0.002076,1.113092,0.197619
1,(avocado),(chocolate),0.045797,0.205217,0.010242,0.223629,1.089716,0.000843,1.023715,0.086281
2,(avocado),(french fries),0.045797,0.192657,0.011594,0.253165,1.314069,0.002771,1.081019,0.250476
3,(avocado),(milk),0.045797,0.170048,0.010821,0.236287,1.389528,0.003034,1.086732,0.293786
4,(avocado),(mineral water),0.045797,0.299710,0.015845,0.345992,1.154421,0.002120,1.070766,0.140185
...,...,...,...,...,...,...,...,...,...,...
350,"(mineral water, shrimp)",(spaghetti),0.033430,0.229565,0.012367,0.369942,1.611491,0.004693,1.222800,0.392580
351,"(spaghetti, soup)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,0.004624,1.469236,0.436362
352,"(soup, mineral water)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,0.003147,1.139190,0.300865
353,"(spaghetti, tomatoes)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,0.004550,1.276999,0.346742
354,"(mineral water, tomatoes)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,0.005586,1.265209,0.427765

# Task 3: Analysis and Interpretation:

**1) Analyse the generated rules to identify interesting patterns and relationships between the products.**

Analyzing the Generated Rules :

Strong Rules:

Look for rules with high confidence and lift.

These rules indicate strong associations that are both frequent and significant.

e.g.: If a rule like milk and bread has a high confidence and lift, it suggests that customers who buy milk are significantly more likely to buy bread compared to the average customer.

Interesting Patterns :

Complementary Products:

Rules that show how certain products are frequently purchased together can suggest complementary products.

Retailers can use this information for product placement or bundling offers.

Substitute Products:

If two products appear together less frequently than expected (low lift), they might be substitutes for each other.

High-Value Products:

If high-value or high-margin items are frequently associated with other products, it might suggest opportunities for cross-selling or upselling.

Example :

Market Basket Insights :

A rule like avocado, milk, and bread might suggest that customers who purchase avocados and milk together are likely to buy bread as well.

This can help design store layouts to place these items near each other.

**2) Interpret the results and provide insights into customer purchasing behavior based on the discovered rules.**

Interpretation of Results :

Customer Preferences:

The patterns reveal what customers prefer to buy together, offering insights into how to stock shelves or design promotions.

Product Relationships:

Understanding which products are often bought together can help in inventory management and reducing out-of-stock situations for commonly paired items.

Strategic Decisions:

Retailers can use these insights for making data-driven decisions regarding pricing, promotions, and store layout to enhance customer experience and boost sales.